version: 1
build:
  main: ./cmd/arkeod
  proto:
    path: proto
    third_party_paths:
    - third_party/proto
    - proto_vendor
genesis:
  chain_id: "arkeo-local"
  app_state:
    staking:
      params:
        bond_denom: "uarkeo"
    claimarkeo:
      module_account_balance:
        denom: ''
        amount: '0'
      params:
        airdrop_start_time: '2024-08-27T04:35:10.833785853Z'
        duration_until_decay: 7884000s
        duration_of_decay: 7884000s
        claim_denom: uarkeo
        initial_gas_amount: 
      claim_records:
        - chain: ARKEO
          address: tarkeo19358z26jwh3e4rd6psxqf8q6f3pe6f8s7v0x2a
          amount_claim:
            denom: uarkeo
            amount: '1000'
          amount_vote:
            denom: uarkeo
            amount: '1000'
          amount_delegate:
            denom: uarkeo
            amount: '1000'
          is_transferable: true
        - chain: ARKEO
          address: tarkeo1dllfyp57l4xj5umqfcqy6c2l3xfk0qk6zpc3t7
          amount_claim:
            denom: uarkeo
            amount: '1000'
          amount_vote:
            denom: uarkeo
            amount: '1000'
          amount_delegate:
            denom: uarkeo
            amount: '1000'
          is_transferable: true
        - chain: ARKEO
          address: tarkeo1xrz7z3zwtpc45xm72tpnevuf3wn53re8q4u4nr
          amount_claim:
            denom: uarkeo
            amount: '1000'
          amount_vote:
            denom: uarkeo
            amount: '1000'
          amount_delegate:
            denom: uarkeo
            amount: '1000'
          is_transferable: true
        - chain: ETHEREUM
          address: '0x92E14917A0508Eb56C90C90619f5F9Adbf49f47d'
          amount_claim:
            denom: uarkeo
            amount: '500000'
          amount_vote:
            denom: uarkeo
            amount: '600000'
          amount_delegate:
            denom: uarkeo
            amount: '700000'
          is_transferable: true


accounts:
- name: reserve
  coins:
  - 2000000000000000uarkeo
- name: alice
  coins:
  - 200000000000000uarkeo
- name: bob
  coins:
  - 1000000000000uarkeo
faucet:
  name: bob
  coins:
  - 5uarkeo
  host: 0.0.0.0:4500
client:
  typescript:
    path: ts-client
  vuex:
    path: vue/src/store
  openapi:
    path: docs/static/openapi.yml
validators:
- name: alice
  bonded: 100000000uarkeo
