version: 1
build:
  main: ./cmd/arkeod
  proto:
    path: proto
    third_party_paths:
    - third_party/proto
    - proto_vendor
genesis:
  chain_id: "arkeo-local"
  app_state:
    staking:
      params:
        bond_denom: "uarkeo"
accounts:
- name: reserve
  coins:
  - 2000000000000000uarkeo
  address: tarkeo1d0m97ywk2y4vq58ud6q5e0r3q9khj9e3unfe4t
- name: alice
  coins:
  - 200000000000000uarkeo
- name: bob
  coins:
  - 1000000000000uarkeo
faucet:
  name: bob
  coins:
  - 5uarkeo
  host: 0.0.0.0:4500
client:
  typescript:
    path: ts-client
  vuex:
    path: vue/src/store
  openapi:
    path: docs/static/openapi.yml
validators:
- name: alice
  bonded: 100000000uarkeo
