name: Arkeo CI
run-name: ${{ github.actor }} is testing a code change ðŸš€
on: [push]

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: "${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}"
  cancel-in-progress: true

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Golang
        uses: actions/setup-go@v3
        with:
          go-version: 1.20.x
          # cache: true
      - name: Compile Protobuf
        run: |
          make proto-gen
      - name: Lint code
        run: |
          make lint-ci
      - name: Unit Tests
        run: |
          sudo rm -rf vue
          make test

  regression-test:
    name: Regression Test
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Golang
        uses: actions/setup-go@v3
        with:
          go-version: 1.20.x
          # cache: true
      - name: Compile Protobuf
        run: |
          make proto-gen
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2
      - name: Regression Tests
        run: |
          make test-regression-ci
